AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - '**/vendor/**/*'

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 118

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
