plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-sorbet
  - rubocop-rails
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "/bin/*"
    - "**/vendor/**/*"
    - "**/sorbet/rbi/annotations/**/*.rbi"

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 118

Metrics/AbcSize:
  Max: 35

Metrics/MethodLength:
  Max: 30

# System tests use Rack::Test which doesn't support have_http_status matcher
RSpecRails/HaveHttpStatus:
  Exclude:
    - "**/spec/system/**/*.rb"

RSpecRails/HttpStatus:
  Exclude:
    - "**/spec/system/**/*.rb"

# This is already the default
Sorbet/FalseSigil:
  Enabled: false

# T::Sig is monkey-patched into Module
Sorbet/RedundantExtendTSig:
  Enabled: true

Sorbet/StrictSigil:
  Enabled: true
  Exclude:
    - "**/config/{routes,puma}.rb"
    - "**/spec/**/*.rb"

Sorbet/TrueSigil:
  Enabled: true
  Exclude:
    - "**/config/{routes,puma}.rb"
    - "**/spec/**/*.rb"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
