gem:
  exclude:
    - addressable
    - actioncable
    - activejob
    - actionmailbox
    - actionmailer
    - activemodel
    - activerecord
    - actiontext
    - activestorage
    - base64
    - benchmark
    - bigdecimal
    - builder
    - connection_pool
    - crass
    - date
    - diff-lcs
    - drb
    - erb
    - faraday-net_http
    - globalid
    - io-console
    - json
    - jwt
    - language_server-protocol
    - logger
    - mail
    - marcel
    - mini_mime
    - multi_xml
    - net-http
    - net-imap
    - net-pop
    - net-protocol
    - net-smtp
    - netrc
    - nio4r
    - oauth2
    - octokit
    - omniauth-rails_csrf_protection
    - parallel
    - pp
    - prettyprint
    - propshaft
    - psych
    - public_suffix
    - puma
    - racc
    - rails-html-sanitizer
    - rdoc
    - reline
    - require-hooks
    - rexml
    - rubocop-performance
    - rubocop-rails
    - rubocop-rspec_rails
    - rubocop-sorbet
    - ruby-progressbar
    - sawyer
    - securerandom
    - snaky_hash
    - stringio
    - timeout
    - tzinfo
    - unicode-display_width
    - unicode-emoji
    - uri
    - useragent
    - version_gem
    - websocket-driver
    - websocket-extensions
    - yard-sorbet
    - yard
    - zeitwerk
dsl:
