# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Time`.
# Please instead update this file by running `bin/tapioca dsl Time`.


class Time
  class << self
    sig { returns(::ActiveSupport::TimeWithZone) }
    def current; end
  end
end
