#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "==> Installing Ruby dependencies..."
bundle check || bundle install
echo

if command -v brew &>/dev/null; then
  echo "==> Installing Homebrew dependencies..."
  brew bundle check || brew bundle
fi
