#!/bin/bash
set -e
cd "$(dirname "$0")/.."

cleanup() {
  if [ -n "$SERVER_PID" ]; then
    kill "$SERVER_PID"
  fi
}

trap "cleanup" EXIT

# assert that any reference of sudo uses -A (or is whitelisted for another reason)
checkSudoAskpass() {
  set +e
  violations=$(
    # find all sudo
    grep "[^']sudo " bin/strap.sh | \
      # filter out comments
      grep -v "^#" | \
      # filter out session resets
      grep -v "sudo -k" | \
      # filter out password prompt
      grep -v "(for sudo access)" | \
      # filter out check to see if sudo is required
      grep -v "sudo -vn &>" | \
      # filter out all correct usages with askpass
      grep -cv "sudo -A"
  )
  set -e
  if [ "$violations" -ne "0" ]; then
    echo "!!! Potential use of sudo in strap.sh script without the -A parameter to enable"
    echo "askpass helper (-A is used to avoid reprompting a user for their sudo password)."
    echo
    echo "Either add -A or add legitimate use to whitelist in cibuild script."
    exit 1
  fi
}

checkSudoAskpass

script/bootstrap
bundle exec foreman check
script/server &>/dev/null &
SERVER_PID="$!"
sleep 15
curl -O http://localhost:5000/strap.sh
kill "$SERVER_PID"
wait "$SERVER_PID" || true
SERVER_PID=

export STRAP_CI=1
export STRAP_DEBUG=1
bash strap.sh

brew install --build-from-source libffi
brew cask install flux
brew install shellcheck

shellcheck strap.sh
